DEBUG 2016-07-01 10:29:05,103: 	 Executing command: 'status'
DEBUG 2016-07-01 10:29:05,103: 	 Found CRAB cache file /afs/desy.de/user/e/eren/.crab3
DEBUG 2016-07-01 10:29:05,111: 	 Checking credentials
DEBUG 2016-07-01 10:29:05,111: 	 Found proxy file /tmp/x509up_u22919
DEBUG 2016-07-01 10:29:05,111: 	 Getting proxy life time left
DEBUG 2016-07-01 10:29:05,814: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u22919 -timeleft
 output : 86281

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2016-07-01 10:29:06,217: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u22919 -actimeleft
 output : 86280

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2016-07-01 10:29:06,217: 	 Proxy valid for 23:58:01 hours
ERROR 2016-07-01 10:29:06,218: 	 Cannot find .requestcache file in CRAB project directory /nfs/dust/cms/user/eren/CMS/InclusiveJets/CMSSW_8_0_7/src/SMPJ/AnalysisFW/test/JetDataWithJsonFile-MagnField-Run2016B_25ns-BTag-80X-PromptReco-v1
ERROR 2016-07-01 10:29:06,219: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 447, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /nfs/dust/cms/user/eren/CMS/InclusiveJets/CMSSW_8_0_7/src/SMPJ/AnalysisFW/test/JetDataWithJsonFile-MagnField-Run2016B_25ns-BTag-80X-PromptReco-v1
DEBUG 2016-07-04 18:17:18,771: 	 Executing command: 'submit'
DEBUG 2016-07-04 18:17:18,772: 	 Found CRAB cache file /afs/desy.de/user/e/eren/.crab3
DEBUG 2016-07-04 18:17:18,792: 	 Checking credentials
DEBUG 2016-07-04 18:17:18,792: 	 Found proxy file /tmp/x509up_u22919
DEBUG 2016-07-04 18:17:18,792: 	 Getting proxy life time left
ERROR 2016-07-04 18:17:19,095: 	 Keyboard Interrupted
DEBUG 2016-07-04 18:17:31,174: 	 Executing command: 'submit'
DEBUG 2016-07-04 18:17:31,174: 	 Found CRAB cache file /afs/desy.de/user/e/eren/.crab3
DEBUG 2016-07-04 18:17:31,181: 	 Checking credentials
DEBUG 2016-07-04 18:17:31,182: 	 Found proxy file /tmp/x509up_u22919
DEBUG 2016-07-04 18:17:31,182: 	 Getting proxy life time left
DEBUG 2016-07-04 18:17:32,085: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u22919 -timeleft
 output : 59464

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2016-07-04 18:17:32,488: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u22919 -actimeleft
 output : 59464

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2016-07-04 18:17:32,488: 	 Proxy valid for 16:31:04 hours
INFO 2016-07-04 18:17:32,489: 	 Will use CRAB configuration file crabDataAODBTag.py
DEBUG 2016-07-04 18:17:32,489: 	 Loading CRAB configuration file.
DEBUG 2016-07-04 18:17:32,492: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-07-04 18:17:32,493: 	 Working area '/nfs/dust/cms/user/eren/CMS/InclusiveJets/CMSSW_8_0_7/src/SMPJ/AnalysisFW/test/JetDataWithJsonFile-MagnField-Run2016B_25ns-BTag-80X-PromptReco-v2/crab_JetData-June2016-MagnField-Run2016B_25ns-BTag-80X-PromptReco-v2' already exists 
Please change the requestName in the config file
ERROR 2016-07-04 18:17:32,493: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 299, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/nfs/dust/cms/user/eren/CMS/InclusiveJets/CMSSW_8_0_7/src/SMPJ/AnalysisFW/test/JetDataWithJsonFile-MagnField-Run2016B_25ns-BTag-80X-PromptReco-v2/crab_JetData-June2016-MagnField-Run2016B_25ns-BTag-80X-PromptReco-v2' already exists 
Please change the requestName in the config file
DEBUG 2016-08-03 11:37:33,212: 	 Executing command: 'submit'
DEBUG 2016-08-03 11:37:33,213: 	 Found CRAB cache file /afs/cern.ch/user/p/pgunnell/.crab3
DEBUG 2016-08-03 11:37:33,229: 	 Checking credentials
DEBUG 2016-08-03 11:37:33,229: 	 Found proxy file /tmp/x509up_u32627
DEBUG 2016-08-03 11:37:33,229: 	 Getting proxy life time left
DEBUG 2016-08-03 11:37:34,033: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u32627 -timeleft
 output : 86328

 error: 
 retcode : 0
DEBUG 2016-08-03 11:37:34,546: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u32627 -actimeleft
 output : 86328

 error: 
 retcode : 0
DEBUG 2016-08-03 11:37:34,546: 	 Proxy valid for 23:58:48 hours
INFO 2016-08-03 11:37:34,546: 	 Will use CRAB configuration file crabDataAODBTag.py
DEBUG 2016-08-03 11:37:34,546: 	 Loading CRAB configuration file.
DEBUG 2016-08-03 11:37:34,547: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-03 11:37:34,548: 	 Working area '/afs/cern.ch/work/p/pgunnell/Run2Analysis/CMSSW_8_0_13_patch1/src/SMPJ/AnalysisFW/test/JetDataWithJsonFile-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/crab_JetData-June2016-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2' already exists 
Please change the requestName in the config file
ERROR 2016-08-03 11:37:34,548: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/p/pgunnell/Run2Analysis/CMSSW_8_0_13_patch1/src/SMPJ/AnalysisFW/test/JetDataWithJsonFile-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/crab_JetData-June2016-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2' already exists 
Please change the requestName in the config file
DEBUG 2016-08-03 18:22:58,334: 	 Executing command: 'status'
DEBUG 2016-08-03 18:22:58,334: 	 Found CRAB cache file /afs/cern.ch/user/p/pgunnell/.crab3
ERROR 2016-08-03 18:22:58,334: 	 Error: JetDataWithJsonFile-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/crab_JetData-June2016-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/ is not a valid CRAB project directory.
ERROR 2016-08-03 18:22:58,334: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 749, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: JetDataWithJsonFile-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/crab_JetData-June2016-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/ is not a valid CRAB project directory.
DEBUG 2016-08-03 18:23:01,830: 	 Executing command: 'status'
DEBUG 2016-08-03 18:23:01,830: 	 Found CRAB cache file /afs/cern.ch/user/p/pgunnell/.crab3
ERROR 2016-08-03 18:23:01,831: 	 Error: JetDataWithJsonFile-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/crab_JetData-June2016-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/ is not a valid CRAB project directory.
ERROR 2016-08-03 18:23:01,831: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 749, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: JetDataWithJsonFile-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/crab_JetData-June2016-MagnField-Run2016D_25ns-BTag-80X-PromptReco-v2/ is not a valid CRAB project directory.
DEBUG 2016-09-26 21:51:00,704: 	 Executing command: 'submit'
DEBUG 2016-09-26 21:51:00,722: 	 Found CRAB cache file /afs/cern.ch/user/p/pgunnell/.crab3
DEBUG 2016-09-26 21:51:00,757: 	 Checking credentials
DEBUG 2016-09-26 21:51:00,757: 	 Proxy file /tmp/x509up_u32627 not found
DEBUG 2016-09-26 21:51:00,757: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-09-26 21:51:04,974: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-09-26 21:51:05,379: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u32627 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u32627 (No such file or directory)

 retcode : 1
ERROR 2016-09-26 21:51:05,379: 	 Error while checking proxy timeleft for /tmp/x509up_u32627
DEBUG 2016-09-26 21:51:05,789: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u32627 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u32627 (No such file or directory)

 retcode : 1
ERROR 2016-09-26 21:51:05,790: 	 Problems creating proxy.
ERROR 2016-09-26 21:51:05,790: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
